#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

### CREATE DIRECTORIES ###
mkdir -p "$logdir" "$datadir" "$datadir/counters"
chown www-data:www-data "$logdir" "$datadir" "$datadir/counters"

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### EDIT FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
[ -e "/home/ueda/rnd" ] && rnd=$(cat /home/ueda/rnd )
mv "fetch" "fetch_$rnd.cgi"

### RESTORE DATADIR ###
rm -rf "$datadir/posts"
rm -rf "$datadir/pages"

### PULL DATA ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
touch "$datadir/INIT"
chown www-data:www-data "$datadir/INIT"
chown www-data:www-data "$contentsdir" -R
sudo -u www-data "$appdir/fetch_$rnd.cgi"

echo "call fetch_$rnd.cgi from GitHub"
